apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: ocscluster
  namespace: ocscluster
spec:
  clusterNamespace: ocscluster
  iamPolicyController:
    enabled: true
  clusterName: ocscluster
  searchCollector:
    enabled: true
  policyController:
    enabled: true
  certPolicyController:
    enabled: true
  version: 2.2.0
  clusterLabels:
    cloud: auto-detect
    name: ocscluster
    vendor: auto-detect
  applicationManager:
    argocdCluster: false
    enabled: true
